package rzahoransky.gui.measureSetup;

public enum MeasureSetupEntry {
	MIEFILE, OUTPUTFILE, MEASURELENGTH_IN_CM, NIADAPTER, STOREINTERVAL, DEVICEWL1, DEVICEWL2, DEVICEWL3, AVERAGE_OVER_TIME, SAMPLES_PER_CHANNEL, MARKER_TYPE;

}
