package rzahoransky.gui.measureSetup;

public enum MeasureSetupEntry {
	MIEFILE, OUTPUTFILE, MEASURELENGTH_IN_CM, NIADAPTER, STOREINTERVAL, DEVICEWL1, DEVICEWL2, DEVICEWL3, AVERAGE_OVER_TIME, SAMPLES_PER_CHANNEL, MARKER_TYPE, RAW_DATA_EXTRACTOR, NI_ADAPTER_CHANNEL, OVERALL_REFRESH_RATE, MEASUREMENT_DIFFERENCE_THRESHOLD, USE_ADAPTIVE_OUTPUT_WRITER, USE_REFERENCE_WL1, USE_REFERENCE_WL2, USE_REFERENCE_WL3;

}
